version: '2'
services:
  db:
    image: 'bitnami/postgresql:12.3.0-debian-10-r56'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=m0v1es_user
      - POSTGRESQL_PASSWORD=sodoucs39sq4v5vv
      - POSTGRESQL_DATABASE=movie_db
  backend:
    depends_on:
      - db
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movie_db
      - SPRING_DATASOURCE_USERNAME=m0v1es_user
      - SPRING_DATASOURCE_PASSWORD=sodoucs39sq4v5vv
    ports:
      - 8080:8080
